name = "dynamic-report"
compatibility_date = "2024-10-31"
compatibility_flags = ["nodejs_compat"]
main = "./server.ts"
assets = { directory = "./build/client" }



[vars]
APP_ENV = "development"
APP_NAME = "Flying Worker"
APP_URL = "http://localhost:8787"
APP_SECRET = "12086fb500fc4bafae7d660773b554c6"
SESSION_DRIVER = "kv"
APP_MAINTENANCE_MODE = true
QUEUE_MODE = true
D1_BINDING_NAME = 'DB'
D1_DB_NAME = 'flying-worker'
QUEUE_BINDING_NAME = 'MY_QUEUE'
KV_BINDING_NAME = 'kv'
SYNC_QUEUE = false


[placement]
mode = "smart"

[[kv_namespaces]]
binding = "kv"
id = "7f2f379205be4f75bda4ac3048d19006"

[[d1_databases]]
binding = "DB"
database_name = "flying-worker"
database_id="5acea7d6-a42f-47f9-8f4a-55b8c46899d9"
migrations_dir = 'migrations'

[ai]
binding = "AI"

[[queues.producers]]
queue = "my-queue"
binding = "MY_QUEUE"

[[queues.consumers]]
queue = "my-queue"
max_batch_size = 1
max_batch_timeout = 60
max_retries = 2
